### ISSUE TITLE
How to download the ready-to-use YFCC100M dataset using your code?

### ISSUE THREAD

**Issue by ghost** [luisremis/visual_storm#6]
Hi, I want to using YFCC to benchmark the performance of VDMS. But it seems that your code in the `tools/downloader` can not work properly.....

Should I download the dataset by myself in advance and store the dataset in the folder?`"/mnt/largedata/yfcc100m/metadata/yfcc100m_dataset_videos"`

**Comment by luisremis** [comment]
yes, you will need to download the dataset to run benchmarks. Scripts to download are in the repo, but they may need some extra work a this point because they have not been updated in a while. Downloading the full dataset will take a long time, and some images may no longer be available online. 
It looks like you are with Intel, so there is an internal copy I worked with in the past. You should talk to @cwlacewe.
